-- Create news table
create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    category text not null, -- 'ประชาสัมพันธ์', 'จัดซื้อจัดจ้าง', 'ประกาศทั่วไป'
    image_url text,
    file_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.news enable row level security;

-- Create policy to allow anonymous reads
create policy "Allow public read access" 
on public.news for select 
using (true);

-- Create policy to allow authenticated users (admin) to manage news
create policy "Allow authenticated CRUD" 
on public.news for all 
to authenticated 
using (true) 
with check (true);

-- Optional: Create staff table if needed later
create table if not exists public.staff (
    id bigint generated by default as identity primary key,
    name text not null,
    position text not null,
    department text not null,
    photo_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.staff enable row level security;

create policy "Allow public staff read access"
on public.staff for select
using (true);

create policy "Allow authenticated staff CRUD"
on public.staff for all
to authenticated
using (true)
with check (true);
